const prisma = require("./client");
const bcrypt = require("bcrypt");
const {createUser} = require("./users");
const {createInterests} = require("./interests");
const {createDestinations} = require("./destinations");
const {createAttractions} = require("./attractions");
const {createUserInterest} = require("./user_interest")

const seed = async() => {

const johnPass = await bcrypt.hash(`${123}`, 5)
const jackPass = await bcrypt.hash(`${456}`, 5)
const jillPass = await bcrypt.hash(`${789}`, 5)

const john = await createUser("john@gmail.com", "John", johnPass, "John", "Johnson", true)
const jack = await createUser("jack@gmail.com", "Jack", jackPass, "Jack", "Jackson")
const jill = await createUser("jill@gmail.com", "Jill", jillPass, "Jill", "Jillson", true)

const culture = await createInterests("Cultural Exploration", "An interest in learning about different cultures.", "https://i.imgur.com/oCsUrNk.jpeg")
const outdoor = await createInterests("Outdoor Adventure", "Seeking adventure outdoors like hiking.", "https://i.imgur.com/AZuhonI.jpeg")
const relaxing = await createInterests("Relaxation", "Unwind and relax.", "https://i.imgur.com/IK1iLPR.jpeg")

const paris = await createDestinations("Paris", "France", `Paris, often referred to as the "City of Love," is a captivating and romantic destination that effortlessly blends rich history with modern allure. Iconic landmarks such as the Eiffel Tower, Louvre Museum, and Notre-Dame Cathedral stand as testaments to the city's cultural and architectural significance. The charming streets are adorned with stylish boutiques, cozy cafes, and world-class restaurants, offering a delightful gastronomic journey for visitors. Whether strolling along the Seine River, exploring the art-lined streets of Montmartre, or savoring delectable pastries in a local patisserie, Paris promises an enchanting experience that captures the heart and imagination of every traveler.`, "April - June", 310, "https://i.imgur.com/sLwRvot.jpeg", "Euro, EUR, (€)", "French", "https://parisjetaime.com/eng")
const bali = await createDestinations("Bali", "Indonesia", `Bali, the "Island of the Gods," is a tropical paradise that beckons travelers with its lush landscapes, vibrant culture, and pristine beaches. Surrounded by azure waters, Bali offers a perfect blend of relaxation and adventure, with world-class surfing spots, lush rice terraces, and ancient temples dotting the landscape. Ubud, the cultural heart of Bali, is a haven for art lovers and those seeking spiritual experiences with its traditional dance performances and artisan markets. Whether exploring the majestic Tanah Lot Temple, indulging in Balinese cuisine, or simply basking in the warm hospitality of the locals, Bali offers a magical escape that captivates the senses and lingers in the hearts of those who visit.`, "April - October", 210, "https://i.imgur.com/UfnXuz9.jpeg", "Indonesian Rupiah, IDR, (Rp)",  "Balinese and Indonesian", "https://bali.com")
const reykjavik = await createDestinations("Reykjavik", "Iceland", `Reykjavik, the vibrant capital of Iceland, is a charming city where modern sophistication meets the raw beauty of nature. Known for its artistic flair, cozy cafes, and colorful street art, Reykjavik offers a unique blend of urban culture against the backdrop of breathtaking landscapes. The Hallgrímskirkja, an iconic church that towers over the city, provides panoramic views of the surrounding mountains and sea. Visitors can also explore the city's lively waterfront, indulge in geothermal spa experiences, and immerse themselves in the Icelandic charm of Reykjavik's bustling streets, making it a captivating destination for both adventure seekers and culture enthusiasts.`, "June - August", 415, "https://i.imgur.com/nPQqqf9.jpeg", " Icelandic Króna, ISK, (kr)", "Icelandic", "https://visitreykjavik.is")
const rome = await createDestinations("Rome", "Italy", `Rome, the eternal city, is a timeless destination that seamlessly intertwines ancient wonders with a vibrant modern lifestyle. Steeped in history, the city boasts iconic landmarks such as the Colosseum, Roman Forum, and the Pantheon, transporting visitors to the heart of the Roman Empire. With its charming cobblestone streets, lively piazzas, and mouthwatering cuisine, Rome invites exploration around every corner. From the Vatican City's magnificent St. Peter's Basilica to the romantic ambiance of the Spanish Steps, Rome is an immersive journey through centuries of art, architecture, and la dolce vita.`, "April - October", 280, "https://i.imgur.com/rHslby2.jpg", "Euro, EUR, (€)", "Italian", "https://www.italia.it/en")
const kyoto = await createDestinations("Kyoto", "Japan", `Kyoto, the cultural jewel of Japan, is a city where ancient traditions seamlessly blend with modern life. Renowned for its breathtaking temples, picturesque gardens, and traditional tea houses, Kyoto offers a serene escape into Japan's rich history. The iconic Fushimi Inari Shrine, adorned with thousands of vermillion torii gates, is a symbol of spiritual beauty and cultural significance. Visitors can immerse themselves in the art of the geisha in the historic Gion district, savor traditional kaiseki cuisine, and witness the ethereal beauty of cherry blossoms in spring, making Kyoto a captivating destination for those seeking a glimpse into Japan's cultural heritage.`, "March - April", 175, "https://i.imgur.com/XmqJONk.jpeg", "Japanese Yen, JPY, (¥)", "Japanese", "https://kyoto.travel/en")
const vancouver = await createDestinations("Vancouver", "Canada", `Vancouver, nestled between the Pacific Ocean and the Coast Mountain range, is a city where natural beauty harmoniously coexists with urban sophistication. Stanley Park, a lush urban oasis, offers scenic seawall paths and vibrant gardens with views of the city skyline and mountains. The bustling Granville Island Public Market showcases a diverse array of local produce, artisan crafts, and delectable food. Vancouver's multicultural neighborhoods, from historic Gastown to the trendy Yaletown, provide a blend of world-class dining, eclectic shopping, and a dynamic arts scene, making it a captivating destination for those seeking a harmonious fusion of city life and outdoor adventure.`, "June - August", 300, "https://i.imgur.com/8zFyy16.jpeg", "Canadian Dollar, CAD ($)", "English and Punjabi", "https://www.destinationvancouver.com")
const maui = await createDestinations("Maui", "United States", `Maui, the second-largest island in Hawaii, is a tropical paradise that captivates visitors with its diverse landscapes and laid-back atmosphere. Known for its pristine beaches, including the iconic Wailea and Kaanapali, Maui offers crystal-clear waters perfect for snorkeling, surfing, and whale watching. The scenic Road to Hana takes travelers on a breathtaking journey through lush rainforests, waterfalls, and dramatic coastline vistas. With its vibrant Hawaiian culture, delicious cuisine, and the majestic Haleakalā National Park, Maui is an idyllic destination that invites exploration and relaxation amid the beauty of the Pacific.`, "December - April", 450, "https://i.imgur.com/nDOoLGP.jpeg", "United States Dollar, USD, ($)", "English", "https://www.gohawaii.com/islands/maui")
const borabora = await createDestinations("Bora Bora", "French Polynesia", `Bora Bora, a tropical haven nestled in the South Pacific, is the epitome of paradise with its iconic overwater bungalows, turquoise lagoons, and stunning coral reefs. Known as one of the most romantic destinations on Earth, Bora Bora offers unparalleled luxury and seclusion for travelers seeking an idyllic escape. Visitors can indulge in water activities like snorkeling, paddleboarding, and shark feeding, surrounded by the vibrant marine life of the lagoon. The lush Mount Otemanu provides a picturesque backdrop to the palm-fringed beaches and luxurious resorts, making Bora Bora a dream destination for those yearning for an unforgettable tropical getaway.`, "May - October", 750, "https://i.imgur.com/TxkoxZv.jpeg", "French Pacific Franc, XPF, (₣)", "French and Tahitian", "https://www.borabora.com")
const santorini = await createDestinations("Santorini", "Greece", `Santorini, a mesmerizing Greek island in the Aegean Sea, is renowned for its enchanting landscapes, stunning sunsets, and unique architecture. The island's iconic white-washed buildings with blue-domed roofs perched on the cliffs create a postcard-perfect scene against the deep blue waters of the caldera. Fira and Oia, the island's main towns, offer a charming blend of narrow cobblestone streets, boutique shops, and traditional tavernas overlooking the sea. Visitors can explore ancient ruins, relax on the distinctive black sand beaches, and experience the warmth of Greek hospitality, making Santorini an idyllic destination for romance, relaxation, and exploration.`, "June - September", 450, "https://i.imgur.com/4DOxqva.jpeg", "Euro, EUR, (€)", "Greek", "https://www.visitgreece.gr/islands/cyclades/santorini")
const barcelona = await createDestinations("Barcelona", "Spain", `Barcelona, the vibrant capital of Catalonia, beckons visitors with its unique blend of rich history, artistic brilliance, and lively Mediterranean spirit. The city is a masterpiece of architecture with Antoni Gaudí's fantastical creations, including the renowned Sagrada Família and the colorful Park Güell. Stroll down the bustling La Rambla, where street performers and open-air markets contribute to the city's energetic ambiance. With its golden beaches, delectable tapas, and a thriving arts scene, Barcelona offers a dynamic and multifaceted experience, making it a must-visit destination for those seeking a perfect harmony between culture, relaxation, and culinary delights.`, "May - August", 250, "https://i.imgur.com/Uhx3HLn.jpeg", "Euro, EUR, (€)", "Catalan and Spanish", "https://www.barcelonaturisme.com/wv3/en")
const london = await createDestinations("London", "England", `London, the dynamic capital of the United Kingdom, stands as a global city that effortlessly balances tradition and modernity. Steeped in history, the city boasts iconic landmarks such as the Tower of London, Buckingham Palace, and the historic Westminster Abbey. The River Thames meanders through the heart of the city, providing a scenic backdrop to cultural institutions like the British Museum and the Tate Modern. With its diverse neighborhoods, world-class theaters, and a cosmopolitan culinary scene, London offers a rich tapestry of experiences, making it an enchanting destination for history enthusiasts, art lovers, and those seeking a taste of contemporary urban life.`, "June - August", 350, "https://i.imgur.com/KKiQy3K.jpeg", "British Pound Sterling, GBP, (£)", "English", "https://www.visitlondon.com")
const capetown = await createDestinations("Cape Town", "South Africa", `Cape Town, nestled between the iconic Table Mountain and the pristine waters of the Atlantic Ocean, is a breathtaking destination that captivates visitors with its natural beauty and cultural richness. The city's iconic skyline, dominated by the flat-topped Table Mountain, provides a dramatic backdrop to its vibrant neighborhoods and historic sites. Visitors can explore the historic Victoria & Alfred Waterfront, ascend Table Mountain for panoramic views, or embark on a scenic drive along the Cape Peninsula. With its diverse landscapes, from golden beaches to lush vineyards, Cape Town offers a perfect blend of outdoor adventures, cultural experiences, and a warm South African welcome, making it an irresistible destination for travelers seeking an unforgettable escape.`, "September - February", 250, "https://i.imgur.com/wXSAhR5.jpeg", "South African Rand, ZAR, (R)", "Afrikaans, English, and Xhosa", "https://www.capetown.travel")
const singapore = await createDestinations("Singapore", "Singapore", `Singapore, a vibrant city-state nestled in Southeast Asia, is a captivating blend of modernity and tradition. This dynamic metropolis boasts futuristic skyscrapers, a world-renowned skyline, and lush green spaces. Visitors can explore cultural enclaves like Chinatown and Little India, savor diverse culinary delights at hawker centers, and marvel at iconic landmarks such as the Marina Bay Sands and Gardens by the Bay. Known for its cleanliness, safety, and efficient public transport, Singapore offers a unique fusion of cultures, making it an irresistible destination for those seeking a harmonious mix of tradition and innovation.`, "December - June", 320, "https://i.imgur.com/PxI4Dk1.jpeg", "Singapore Dollar, SGD, ($)", "English, Mandarin, Malay, and Tamil", "https://www.visitsingapore.com/en")
const sydney = await createDestinations("Sydney", "Australia", `Sydney, Australia's dazzling harbor city, captures the essence of cosmopolitan living against the backdrop of iconic landmarks. The Sydney Opera House, with its distinctive sail-like architecture, stands as a symbol of the city's cultural vibrancy, while the Sydney Harbour Bridge offers breathtaking views of the harbor and skyline. Bondi Beach, known worldwide for its golden sands and surf culture, beckons visitors to relax and soak up the sun. The city's diverse neighborhoods, world-class dining, and the lush Royal Botanic Garden contribute to Sydney's appeal as a dynamic destination where urban sophistication meets natural beauty.`, "December - February", 400, "https://i.imgur.com/tGrynYf.jpeg", "Australian Dollar, AUD, ($)", "English", "https://www.sydney.com")
const rio = await createDestinations("Rio de Janeiro", "Brazil", `Rio de Janeiro, the "Cidade Maravilhosa" (Marvelous City) of Brazil, is a vibrant and lively destination nestled between lush mountains and stunning beaches. The iconic Christ the Redeemer statue stands sentinel atop Corcovado Mountain, offering panoramic views of the city below. Copacabana and Ipanema beaches are renowned for their golden sands and pulsating energy, attracting sunseekers, surfers, and revelers alike. With its lively samba-infused culture, annual Carnival festivities, and diverse neighborhoods like Santa Teresa and Lapa, Rio de Janeiro captivates visitors with its infectious rhythm, natural beauty, and a zest for life that makes it an unforgettable destination.`, "December - March", 285, "https://i.imgur.com/ctFHZ33.jpeg", "Brazilian Real, BRL, (R$)", "Portuguese", "https://www.riodejaneiro.com")
const phuket = await createDestinations("Phuket", "Thailand", `Phuket, Thailand's largest island, is a tropical paradise that entices travelers with its stunning beaches, vibrant nightlife, and cultural attractions. White sandy shores like Patong, Karon, and Kata offer idyllic settings for sunbathing and water activities, while the bustling markets and lively streets of Old Phuket Town showcase a rich blend of Thai and colonial architecture. The island is a gateway to the breathtaking Phi Phi Islands and the famous James Bond Island, making it a haven for island-hopping adventures. With its luxurious resorts, delectable street food, and a vibrant atmosphere, Phuket remains a sought-after destination that seamlessly combines relaxation, adventure, and Thai hospitality.`, "November - April", 215, "https://i.imgur.com/W2F24l3.jpeg", "Thai Baht, THB, (฿)", "Thai", "https://www.tourismthailand.org/Destinations/Provinces/Phuket/350")
const dubai = await createDestinations("Dubai", "United Arab Emirates (UAE)", `Dubai, a dazzling metropolis in the heart of the United Arab Emirates, stands as a testament to architectural marvels, opulence, and cutting-edge innovation. The city's iconic skyline is punctuated by the towering Burj Khalifa, the world's tallest building, while the Palm Jumeirah and Burj Al Arab add to its futuristic allure. Dubai Mall, a shopping and entertainment extravaganza, offers a world-class retail experience with the added charm of the Dubai Fountain. From desert safaris and luxury resorts to indoor skiing at the Mall of the Emirates, Dubai seamlessly blends modern luxury with Arabian traditions, creating an unparalleled destination for those seeking extravagance and cultural diversity.`, "November - March", 320, "https://i.imgur.com/R49BbXH.jpeg", "UAE Dirham, AED, (Dh)", "Arabic and English", "https://www.visitdubai.com/en")
const berlin = await createDestinations("Berlin", "Germany", `Berlin, the vibrant capital of Germany, is a city that resonates with history, creativity, and a dynamic cultural scene. The remnants of the Berlin Wall, Checkpoint Charlie, and the historic Brandenburg Gate bear witness to the city's tumultuous past, while contemporary art installations and a thriving nightlife showcase its present-day energy. Museumsinsel (Museum Island) offers a treasure trove of art and history, housing world-class collections within its architectural marvels. Visitors can explore the eclectic neighborhoods of Kreuzberg and Prenzlauer Berg, indulge in the city's diverse culinary scene, and revel in the open spaces of Tiergarten, making Berlin a fascinating destination that seamlessly blends tradition and modernity.`, "May - August", 220, "https://i.imgur.com/CdpXBqv.jpeg", "Euro, EUR, (€)", "German", "https://www.berlin.de/en/tourism")
const moscow = await createDestinations("Moscow", "Russia", `Moscow, the capital of Russia, is a city where grandeur meets modernity, offering a rich tapestry of history, culture, and architectural marvels. The iconic Red Square, flanked by the colorful domes of St. Basil's Cathedral and the historic walls of the Kremlin, serves as the heart of the city's historic center. The Bolshoi Theatre, synonymous with classical ballet and opera, showcases Moscow's enduring commitment to the arts. Visitors can explore the vast collections of the State Tretyakov Gallery, stroll along the Arbat, a lively pedestrian street lined with shops and cafes, and witness the intricate Moscow Metro stations, combining to make Moscow an enchanting destination that reflects the grandeur of Russian heritage.`, "May - August", 200, "https://i.imgur.com/EJ5wHtY.jpeg", "Russian Ruble, RUB, (₽)", "Russian", "https://www.introducingmoscow.com")
const beijing = await createDestinations("Beijing", "China", `Beijing, the capital of China, is a city where ancient history seamlessly intertwines with modern innovation, offering a captivating journey through time. The historic Forbidden City, an imperial palace complex, reveals the splendor of China's imperial past, while the iconic Temple of Heaven stands as a testament to architectural brilliance. The Great Wall of China, a world wonder, winds its way through the mountains surrounding the city, offering breathtaking views of the surrounding landscapes. Beijing's bustling markets, vibrant street life, and contemporary landmarks like the Bird's Nest stadium create a dynamic cityscape that captures the essence of China's cultural richness and rapid development.`, "April - June and September - October", 210, "https://i.imgur.com/cElmnDw.jpeg", "Chinese Yuan Renminbi, CNY, (¥)", "Mandarin and Putonghua", "https://english.visitbeijing.com.cn")
const queenstown = await createDestinations("Queenstown", "New Zealand", `Nestled within New Zealand's Southern Alps, Queenstown stands as a breathtaking jewel and a hub for adrenaline-fueled adventures. Surrounded by crystal-clear lakes and dramatic mountain peaks, the town is renowned for its stunning landscapes that have captivated filmmakers and travelers alike. Queenstown is a haven for outdoor enthusiasts, offering a plethora of activities such as bungee jumping, skiing, hiking, and jet boating, ensuring an adrenaline rush for thrill-seekers. Beyond the adrenaline, the town also boasts a vibrant arts and culinary scene, with charming streets lined with shops, galleries, and restaurants, making Queenstown a well-rounded destination for both adventure and relaxation.`, "December - February", 380, "https://i.imgur.com/G4wF9Sk.jpeg", "New Zealand Dollar, NZD, ($)", "English", "https://www.queenstownnz.co.nz")

const eiffel = await createAttractions("Eiffel Tower", "https://i.imgur.com/romvYx4.jpeg", paris.id)
const louvre = await createAttractions("Louvre", "https://i.imgur.com/yVYUYIB.jpeg", paris.id)
const notreDame = await createAttractions("Notre Dame", "https://i.imgur.com/qNhgLHI.jpeg", paris.id)

const temple = await createAttractions("Uluwatu Temple", "https://i.imgur.com/txhMihx.jpeg", bali.id)
const monkey = await createAttractions("Ubud Monkey Forest", "https://i.imgur.com/v8zb4nN.jpeg", bali.id)
const terrace = await createAttractions("Tegallalang Rice Terraces", "https://i.imgur.com/7vpNMHc.jpeg", bali.id)

const church = await createAttractions("Hallgrímskirkja", "https://i.imgur.com/MZAeagd.jpeg", reykjavik.id)
const sculpture = await createAttractions("The Sun Voyager (Sólfar)", "https://i.imgur.com/dUiPopa.jpeg", reykjavik.id)
const lake = await createAttractions("Tjörnin Lake", "https://i.imgur.com/Now55Qu.jpeg", reykjavik.id)

const colosseum = await createAttractions("Colosseum ", "https://i.imgur.com/VB9ExjP.jpeg", rome.id)
const vatican = await createAttractions("Vatican City", "https://i.imgur.com/nAieozr.jpeg", rome.id)
const pantheon = await createAttractions("Pantheon", "https://i.imgur.com/30t3Jfw.jpg", rome.id)

const zenTemple = await createAttractions("Kinkakuji (金閣寺, Golden Pavilion)", "https://i.imgur.com/wmK572p.jpeg", kyoto.id)
const shrine = await createAttractions("Fushimi Inari Shrine (伏見稲荷大社)", "https://i.imgur.com/YQXiHZU.jpeg", kyoto.id)
const grove = await createAttractions("Arashiyama (嵐山) Bamboo Grove", "https://i.imgur.com/BiVT4Cd.jpeg", kyoto.id)

const park = await createAttractions("Stanley Park", "https://i.imgur.com/PwMCu5A.jpeg", vancouver.id)
const mountain = await createAttractions("Grouse Mountain", "https://i.imgur.com/wiabDdc.jpeg", vancouver.id)
const regionalPark = await createAttractions("Pacific Spirit Regional Park", "https://i.imgur.com/4WQeSnV.jpeg", vancouver.id)

const john_culture = await createUserInterest(john.id, culture.id)
const jack_outdoor = await createUserInterest(jack.id, outdoor.id)
const jill_relaxing = await createUserInterest(jill.id, relaxing.id)

}
seed()

.then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });